### Obtener todas las rutinas
GET http://127.0.0.1:3000/api/ejercicios HTTP/1.1

###

### Obtener una rutina por ID
GET http://127.0.0.1:3000/api/ejercicios/1 HTTP/1.1
# 👆 reemplazá el ID por uno real de tu colección en MongoDB

###

### Crear una nueva rutina
POST http://127.0.0.1:3000/api/ejercicios HTTP/1.1
Content-Type: application/json

{
  "nombre": "press banca",
  "musculo": "pechoooooo"
}

###

### Actualizar una rutina existente
PUT http://127.0.0.1:3000/api/rutinas/672f1b8f0d9f8b1234567890 HTTP/1.1
Content-Type: application/json

{
  "nombre": "Rutina de fuerza avanzada",
  "objetivo": "Incrementar fuerza máxima",
  "tipo": "Powerlifting"
}

###

### Eliminar una rutina
DELETE http://127.0.0.1:3000/api/ejercicios/69153e0bfff5d7e03f9a593a HTTP/1.1
#
